/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chorten.glb')
  useFrame(()=> (group.current.rotation.y -=0.01));
  return (
    <group ref={group} {...props} dispose={null} position={[0,-2,0]}>
      <mesh
        geometry={nodes.BezierCurve004.geometry}
        material={materials['Material.005']}
        position={[-0.04, 5.25, 0.42]}
        rotation={[-1.58, 0.07, -0.01]}
        scale={[0.28, 0.2, 0.29]}
      />
      <group position={[0, 3.01, 0]} rotation={[0, 0, 0.96]} scale={0.03}>
        <mesh geometry={nodes.Circle012_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle012_2.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Circle012_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Circle012_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Circle012_5.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Circle012_6.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Circle012_7.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Circle012_8.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

useGLTF.preload('/chorten.glb')
