/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/greeting.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.anime.play()
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0, -1, 0]} rotation={[0,20,0]}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Avatar"
        geometry={nodes.Wolf3D_Avatar.geometry}
        material={materials['Material.002']}
        skeleton={nodes.Wolf3D_Avatar.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
        
      />
    </group>
  )
}

useGLTF.preload('/greeting.glb')
