/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/working.glb')
  const { actions } = useAnimations(animations, group)
  useFrame(()=> (group.current.rotation.y +=0.01));
  useEffect(() => {
    actions.Working.play()
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0.4,-0.4,0]}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Avatar"
        geometry={nodes.Wolf3D_Avatar.geometry}
        material={materials['Material.001']}
        skeleton={nodes.Wolf3D_Avatar.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[-0.6, -0.1, 0.27]}
        scale={[1.42, 0.91, 0.91]}
      />
      <group position={[-0.25, 0.74, 0.62]} scale={[0.06, 0.02, 0.07]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube022_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube022_4.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube022_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube022_6.geometry} material={materials['Metal Plates']} />
        <mesh geometry={nodes.Cube022_7.geometry} material={materials.CP_Camera} />
        <mesh geometry={nodes.Cube022_8.geometry} material={materials['CP_Screen Side']} />
        <mesh geometry={nodes.Cube022_9.geometry} material={materials['CP_Light Emi']} />
        <mesh geometry={nodes.Cube022_10.geometry} material={materials.CP_Carbon} />
        <mesh geometry={nodes.Cube022_11.geometry} material={materials.CP_Matte} />
        <mesh geometry={nodes.Cube022_12.geometry} material={materials.CP_Screen} />
        <mesh geometry={nodes.Cube022_13.geometry} material={materials.CP_Metal} />
        <mesh geometry={nodes.Cube022_14.geometry} material={materials.CP_Gold} />
        <mesh geometry={nodes.Cube022_15.geometry} material={materials.CP_Glass} />
        <mesh geometry={nodes.Cube022_16.geometry} material={materials['CP_Light Emi 2']} />
        <mesh geometry={nodes.Cube022_17.geometry} material={materials['CP_Light Green']} />
        <mesh geometry={nodes.Cube022_18.geometry} material={materials['CP_flash glass']} />
        <mesh geometry={nodes.Cube022_19.geometry} material={materials['CP_Screen Side 02']} />
        <mesh geometry={nodes.Cube022_20.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube022_21.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube022_22.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube022_23.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube022_24.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube022_25.geometry} material={materials['Leather sofa']} />
        <mesh geometry={nodes.Cube022_26.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/working.glb')
